version: '3'

services:
  php:
    image: php:${PHP_VERSION:-7.1}-fpm
    volumes:
      - ./src:/var/www/pimcore
    links:
      - db:db

  www:
    image: nginx:${NGINX_VERSION:-1.13.9}
    volumes:
      - ./src:/var/www/pimcore
      - ./docker/www/nginx/pimcore.loc.conf:/etc/nginx/conf.d/pimcore.loc.conf
      - ./docker/www/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
    links:
      - php
    ports:
     - "${NGINX_HOST_HTTP_PORT:-80}:80"
     - "${NGINX_HOST_HTTPS_PORT:-443}:443"
      
  db:
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-pimcore}
      MYSQL_USER: ${MYSQL_USER:-pimcore}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-pimcore}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - pimcore5-database:/var/lib/mysql #TODO: change it for mariadb etc. (env variable?)
    ports:
      - "${MYSQL_HOST_PORT:-3306}:3306"
     
volumes:
  pimcore5-database: