version: '3'

services:
  php:
    build:
      context: docker/php
    volumes:
      - ${APPLICATION:-./pimcore}:${CONTAINER_APPLICATION_PATH-/var/www/pimcore}
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    expose:
      - "9000"
    links:
      - db:db

  www:
    image: nginx:${NGINX_VERSION:-1.13.9}
    volumes:
      - ./src:/var/www/pimcore
      - ./docker/www/nginx/pimcore.loc.conf:/etc/nginx/conf.d/pimcore.loc.conf
      - ./docker/www/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
    links:
      - php
    ports:
     - "${NGINX_HOST_HTTP_PORT:-80}:80"
     - "${NGINX_HOST_HTTPS_PORT:-443}:443"
      
  db:
    image: mysql:${MYSQL_VERSION:-8.0}
    volumes:
      - ".data/mysql:/var/lib/mysql"
      - ${APPLICATION:-./pimcore}:${CONTAINER_APPLICATION_PATH-/var/www/pimcore}
      - ./docker/mysql/default.cnf:/etc/mysql/conf.d/default.cnf
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-pimcore}
      MYSQL_USER: ${MYSQL_USER:-pimcore}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-pimcore}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - "${MYSQL_HOST_PORT:-3306}:3306"

  composer:
    image: composer:1.6.3
    volumes:
      - ./src:/app
    command: composer install --ignore-platform-reqs --no-scripts #TODO: change it (quick woraround for now php extensions)


  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "${MAILCATCHER_HOST_PORT}:1080"

  redis:
    image: redis:latest
    ports:
      - ${REDIS_HOST_PORT:-6379}:6379
    volumes:
      - ./.redis-data:/var/lib/redis