version: '3'

services:
  php:
    image: divante/pimcore-docker-php-fpm
    volumes:
      - ${APPLICATION:-./pimcore}:${CONTAINER_APPLICATION_PATH-/var/www/pimcore}
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    expose:
      - "9000"
    links:
      - mysql:mysql

  www:
    image: nginx:${NGINX_VERSION:-1.13.9}
    volumes:
      - ${APPLICATION:-./pimcore}:${CONTAINER_APPLICATION_PATH-/var/www/pimcore}
      - ./docker/www/nginx/pimcore.loc.conf:/etc/nginx/conf.d/pimcore.loc.conf
      - ./docker/www/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
    links:
      - php
    ports:
     - "${NGINX_HOST_HTTP_PORT:-80}:80"
     - "${NGINX_HOST_HTTPS_PORT:-443}:443"

  mysql:
    image: percona:${MYSQL_VERSION:-5.7.21}
    volumes:
      - ".data/mysql:/var/lib/mysql"
      - ${APPLICATION:-./pimcore}:/var/www/pimcore
      - ./docker/mysql/default.cnf:/etc/mysql/conf.d/default.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-database}
      - DOMAIN_NAME=redis.${BASEHOST:-pimcore.loc}
    ports:
      - "${MYSQL_HOST_PORT:-3306}:3306"
    restart: always
    working_dir: /var/www/pimcore

  composer:
    image: divante/pimcore-docker-composer
    volumes:
      - ${APPLICATION:-./pimcore}:${CONTAINER_APPLICATION_PATH-/var/www/pimcore}
    working_dir: ${CONTAINER_APPLICATION_PATH-/var/www/pimcore}
    command: composer install --ignore-platform-reqs --no-scripts #TODO: change it (quick woraround for now php extensions)

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "${MAILCATCHER_HOST_PORT:-1080}:1080"

  redis:
    image: redis:latest
    ports:
      - ${REDIS_HOST_PORT:-6379}:6379
    volumes:
      - ./.redis-data:/var/lib/redis
